
global:
  scrape_interval:     15s
  evaluation_interval: 15s

# scrape the configuration
scrape_configs:
  - job_name: 'kasa'
    static_configs:
    - targets:
    # IP of your smart plugs
      - 10.10.1.56
      - 10.10.1.54
      - 10.10.1.93
      - 10.10.1.111
      - 10.10.1.131
      - 10.10.1.214
    metrics_path: /scrape
    relabel_configs:
      - source_labels : [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        # IP of the exporter
        replacement: tp-link-plug-exporter-local:9233

# scrape kasa_exporter itself
  - job_name: 'kasa_exporter'
    static_configs:
      - targets:
        - tp-link-plug-exporter-local:9233

